title: PISE notes
include:
  - '_pages'
exclude:
  - '_includes/notes_graph.json'
  - '_notes/templates/'
  - '_notes/obsidian.css'
  - '_notes/.obsidian/'
  - 'to-publish/'
  - 'copyrighted-content/'
  - '_notes/lecture template.md'
  - "_notes/**/private/*"
  - "_notes/**/copyrighted-content/*"
baseurl:             /
url:                 "https://pise-notes.club"
description: >-
  Notes from PISE classes at Ca’Foscari University in Venice
author: tommi
permalink:           pretty
relative_permalinks: false
image: "/assets/pise-notes.jpg"

plugins:
  - jekyll-last-modified-at
  - jekyll-feed
  - jekyll-sitemap
#  - jekyll-target-blank # no compatibility with bidirectional links plugin
  - jekyll-redirect-from
  - jekyll-optional-front-matter
  - jekyll-email-protect
#  - jekyll-pdf
#  - jekyll-mermaid

sass:
  sass_dir: _sass
  style: :compressed

collections:
  notes:
    output: true
    permalink: /:title

defaults:
  - scope:
      path: "**/*"
    values:
      layout: "default"
      image: "/assets/pise-notes.jpg"
      author: "tommi"
  - scope:
      path: "_notes/**/*.md"
    values:
      layout: "note"
      author: "tommi"
      image: "/assets/pise-notes.jpg"
# Courses
  - scope:
      path: "_notes/Contemporary History/"
    values:
      course: "Contemporary History"
  - scope:
      path: "_notes/History of Economic Thought/"
    values:
      course: "History of Economic Thought"
  - scope:
      path: "_notes/Introduction to Politics/"
    values:
      course: "Introduction to Politics"
  - scope:
      path: "_notes/Introduction to Economics/"
    values:
      course: "Introduction to Economics"
  - scope:
      path: "_notes/Introduction to Philosophy/"
    values:
      course: "Introduction to Philosophy"
  - scope:
      path: "_notes/Modern Sociology/"
    values:
      course: "Modern Sociology"
  - scope:
      path: "_notes/International Economics and Development Studies/"
    values:
      course: "International Economics and Development Studies"
  - scope:
      path: "_notes/Logic and Philosophy of Science I/"
    values:
      course: "Logic and Philosophy of Science I"
  - scope:
      path: "_notes/Population History/"
    values:
      course: "Population History"
  - scope:
      path: "_notes/Mathematics for Social Sciences/"
    values:
      course: "Mathematics for Social Sciences"
