title:               PISE notes
include:             ['_pages']
exclude:             ['_includes/notes_graph.json', '_notes/templates/', '_notes/obsidian.css']
baseurl:             /
url:                 "https://pise-notes.tk"
description: >-
  Notes from PISE classes at Ca' Foscari university in Venice
permalink:           pretty
relative_permalinks: false

plugins:
  - jekyll-last-modified-at
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-sitemap
#  - jekyll-target-blank # no compatibility with bidirectional links plugin
  - jekyll-redirect-from
  - jekyll-optional-front-matter

sass:
  sass_dir: _sass
  style: :compressed

collections:
  notes:
    output: true
    permalink: /:title

defaults:
  - scope:
      path: "**/*"
    values:
      layout: "default"
  - scope:
      path: "_notes/**/*.md"
    values:
      layout: "note"
